### PR TITLE
first hidden div, replace var with const, arrow notation

### PR DESCRIPTION
**Pull request by zverbatim**
#8

### CODE REVIEW

**Review by yet-another-lucas — CHANGES_REQUESTED** [review]
Thanks, the hidden page is great.

However can you revert the refactoring included in this PR? We are still discussing what coding standard we want to adopt so those changes are premature.

**Comment by zverbatim** [comment]
@yet-another-lucas ah, ok. can you please explain what do you mean by "revert the refactoring"?
I'll keep an eye on #8 
thanks

**Comment by yet-another-lucas** [comment]
@zverbatim Sorry to be unclear, but I meant arrow functions and other changes made outside of that hidden page. To be honest now that I look the next day, I think it should be fine.

**Review by yet-another-lucas — APPROVED** [review]
This is great work, thanks!

**Pull request merged**
